# Generated by Django 6.0.3 on 2026-03-29 01:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product')),
                ('shop', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shop/Branch')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost Price')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Default Selling Price')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RESTOCK', 'Restock (Add Stock)'), ('SALES_CHECK', 'Audit (Record Sales & Profit)')], max_length=20)),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity Added')),
                ('prev_remaining', models.IntegerField(default=0, verbose_name='Previous Count')),
                ('current_remaining', models.IntegerField(default=0, verbose_name='Current Count')),
                ('sell_price_used', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sell Price Used')),
                ('units_used', models.IntegerField(default=0, verbose_name='Units Used')),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Profit Earned')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tracker.product')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
