# Generated by Django 6.0.3 on 2026-08-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_dailysale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysale',
            name='quantity_sold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Sold'),
        ),
    ]
