# Generated by Django 6.0.3 on 2026-08-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_dailysale_quantity_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysale',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Buying Price Used'),
        ),
    ]
