# Generated by Django 6.0.3 on 2026-08-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_dailysale_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysale',
            name='shop',
            field=models.CharField(blank=True, choices=[('Fig Tree', 'Fig Tree'), ('Empire Shop', 'Empire Shop'), ('Emirates', 'Emirates'), ('Small City', 'Small City')], default='', max_length=50, verbose_name='Shop'),
        ),
    ]
