# Generated by Django 6.0.3 on 2026-08-13 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_dailysale_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductShopPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(choices=[('Fig Tree', 'Fig Tree'), ('Empire Shop', 'Empire Shop'), ('Emirates', 'Emirates'), ('Small City', 'Small City')], max_length=50, verbose_name='Shop')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_prices', to='tracker.product')),
            ],
            options={
                'verbose_name': 'Shop Price Override',
                'verbose_name_plural': 'Shop Price Overrides',
                'unique_together': {('product', 'shop')},
            },
        ),
    ]
