# Generated by Django 6.0.3 on 2026-08-15 07:07

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_productshopprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(blank=True, choices=[('Fig Tree', 'Fig Tree'), ('Empire Shop', 'Empire Shop'), ('Emirates', 'Emirates'), ('Small City', 'Small City')], default='', max_length=50, verbose_name='Shop')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Expense',
                'verbose_name_plural': 'Daily Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
