# Generated by Django 6.0.3 on 2026-08-26 20:47

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_dailyexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(blank=True, choices=[('Fig Tree', 'Fig Tree'), ('Empire Shop', 'Empire Shop'), ('Emirates', 'Emirates'), ('Small City', 'Small City')], default='', max_length=50, verbose_name='Shop')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Sales')),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Profit')),
                ('total_expenditure', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Expenditure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Day Totals',
                'verbose_name_plural': 'Day Totals',
                'ordering': ['-date', 'shop'],
                'unique_together': {('shop', 'date')},
            },
        ),
    ]
